### PR TITLE
Mailcomposer

### PR DESCRIPTION
**Pull request by GreenPioneer**
Translated some Chinese 
Switched over to mail composer 
Added Attachfile Example
Added MeetingRequest Example
Updated Simple.js Example
Updated Readme

### CODE REVIEW

**Comment by GreenPioneer** [comment]
Hey Gui,

I have been your package now for a couple year cause it really help for the ease of use with email. Lately i started noticed it was limited in the sense of what i could add to the email. So i went in search of a better way to create the email and potentially send it through your way. this is what i came up with - https://www.npmjs.com/package/mailcomposer . It was extremely easy to insert and i think it really adds huge benefit to your package.

Let me know if you have any question 

Green Pioneer

**Comment by GreenPioneer** [comment]
@guileen  let me know your thoughts on this

**Comment by guileen** [comment]
I think, it's no need to integrate `mailcomposer`, because mailcomposer is a mail builder, and `sendmail` is a mail sender, they work on different level.

But if sendmail is not fit well with mailcomposer, then I think sendmail would make some change to fit that, but not integrate mailcomposer.

And some guild documentation of use mailcomposer with sendmail would be enough.

**Comment by GreenPioneer** [comment]
My point to using it is your trying to build mail yourself.. [Here](https://github.com/guileen/node-sendmail/blob/master/sendmail.js#L253-L294) . What mail composer will do for us its allow use to build more advanced emails like meeting request. We will then use sendmail to send it out .

can you show me a way currently in the current version how to send a meeting request ?

**Comment by guileen** [comment]
You are right.

**Pull request merged**
