### PR TITLE
added devHost option

### PR DESCRIPTION
**Pull request by hdon**
## Description
Add option to override "localhost" when sending all SMTP traffic to a dummy server. 

## Motivation and Context
It's a simple addition and makes the testing behavior a little more flexible.

Actually though I already have an SMTP server and adding this was a cheap way to direct my email through that server.

## How Has This Been Tested?
Works for me.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by GreenPioneer** [comment]
im traveling and will look at this next week

**Comment by GreenPioneer** [comment]
@hdon hey donny how did you test that it works for you ?

**Comment by hdon** [comment]
@GreenPioneer I'm actually using it to send email through our SMTP server.

**Comment by hdon** [comment]
Is there going to be any movement on this?

**Comment by GreenPioneer** [comment]
@hdon sorry i took so long on this. Got it in now thank you very much for you work

**Pull request merged**
