### PR TITLE
Updated sendmail.js to ES2015 | Updated Readme.md to ES2015 | Updated…

### PR DESCRIPTION
**Pull request by Geex-Renzo**
# Updated to ES2015

## Description
All `var` statements are updated to `const` and `let`.
Semicolons(`;`) have been added to all lines, since it's easier for the Javascript parser to work with.
I have not updated callback functions to arrow functions, since it could change the `this` context and it could possibly break the project. This should be done after tests are written, to make sure it's all still working.

This is a "breaking" change, since a pre `ES2015` env would crash on the `const` and `let` usage.

## How Has This Been Tested?
Uploaded code to own server and send mails to myself.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change) 

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes. (No tests have been written so far)
- [ ] All new and existing tests passed. (No tests have been written so far)

### CODE REVIEW

**Comment by Geex-Renzo** [comment]
Related to #25

**Comment by GreenPioneer** [comment]
I am gonna bump this to version 2.0.0 because for the people still on older versions of node this will break it for them. This is mainly for the enterprise users out there.

**Comment by Geex-Renzo** [comment]
No problem, just remember that more code changes could lead to this commit / PR being worthless, since it'll need to be done all-over again ;)

**Comment by GreenPioneer** [comment]
Are you say that because people will want 1.1.0 upgraded too?

**Comment by Geex-Renzo** [comment]
What I meant is that if another thing like the DKIM implementation is added, this PR will no longer be conflict free and it's possible what I did needs to be re-done.

For example:
#### Original:
```
1| var foo = 100;
2| foo = foo.toString();
3| var bar = foo + 'baz';
```
#### PR:
```
1| let foo = 100;
2| foo = foo.toString();
3| const bar = foo + 'baz';
```
#### Added module in between
```
1| var foo = 100;
2| foo = process.env.NODE_ENV === 'production' ? foo.toString() : 'qux';
3| var bar = foo === 'quz' ? 'dev mode' : foo + 'baz';
```

It's a bit random what I did in the last part, but I wanted to make clear that the PR doesn't add up with the original anymore if there is a new module (or something else) added in between, e.g. for testing purposes.

**Comment by Geex-Renzo** [comment]
Also, small comment: when a package is published as a certain version number, it's impossible with NPM to publish something else with the same version number.
For example, if you want the changes I made for #26 to appear on npm, it'll have to be under a different version number than 1.1.0, for example under v1.1.1

**Comment by GreenPioneer** [comment]
Yea get what your saying - following [Semantic Versioning](https://docs.npmjs.com/getting-started/semantic-versioning) though deems that we need to bump it pass 1.x to 2.x because we will stop support Node `0.6.x -  0.12.x` which we currently do and most people dont know it.

To the point of your PR ill get it in tonight or in the morning so that its not worthless

**Comment by Geex-Renzo** [comment]
You're 100% right on the Semantic Versioning part, that's also why I marked it as a breaking change in the initial PR comment and the comment I made about #26.  
And yes, I know 1.x support 0.6x - 0.12.x as I have also updated the `package.json` with the new node engine requirement.

**Comment by GreenPioneer** [comment]
I was working with it a little cause if were going es6 we might as well analyze the code a little more and see what we can make more efficient in es6. It did make me think .... that it would be smarter if i take one step back and write some baseline test cases while we know everything is working great #28 . Im gonna get started on it tomorrow unless you have something already in mind @Geex-Renzo

**Comment by Geex-Renzo** [comment]
Going to respond to #28 in a bit, gimme a sec

**Comment by Geex-Renzo** [comment]
@GreenPioneer Have you seen my comment at #28 ?

**Comment by GreenPioneer** [comment]
Yea @Geex-Renzo  i saw. With it being the holiday ill try to get to it asap

**Pull request merged**
