### PR TITLE
add custom smtp port to options

### PR DESCRIPTION
**Pull request by phungthanhdong**
## Description
Add {smtpPort: <your_port> } to init options. If not defined, the default port 25 will be used.

### CODE REVIEW

**Comment by mvattuone** [comment]
This would be useful.

**Comment by GreenPioneer** [comment]
Im really sorry this took me so long to get around to

**Comment by GreenPioneer** [comment]
@phungthanhdong  thank you for your pr

**Comment by GreenPioneer** [comment]
@phungthanhdong & @mvattuone  - [updated](https://www.npmjs.com/package/sendmail) 1.3.0

**Pull request merged**
